#!/usr/bin/env bash
# Builds catalog/index.json + catalog/index.md from skills/*/SKILL.md frontmatter, per
# specs/006-help-skill/contracts/catalog.schema.json (supersedes
# specs/001-multi-agent-skill-suite/contracts/catalog.schema.json by adding "usage").
#
# Usage: .highway/tools/generate-catalog.sh
# Exit 0: catalog written.
# Exit 1: at least one skill under skills/ is invalid; the catalog is NOT written (no partial
#         catalog), and the failing skill's id is named in the error output.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# HIGHWAY_ROOT is the .highway/ framework root; distinct from the true repo root (see
# specs/002-highway-folder-consolidation/research.md Decision 1). This script never writes
# outside .highway/, so it needs no separate REPO_ROOT.
HIGHWAY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=tools/lib/frontmatter.sh
source "$SCRIPT_DIR/lib/frontmatter.sh"

SKILLS_DIR="$HIGHWAY_ROOT/skills"
CATALOG_DIR="$HIGHWAY_ROOT/catalog"
CATALOG_JSON="$CATALOG_DIR/index.json"
CATALOG_MD="$CATALOG_DIR/index.md"

json_escape() {
	sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

shopt -s nullglob
skill_dirs=("$SKILLS_DIR"/*/)
shopt -u nullglob
skill_count=${#skill_dirs[@]}

# Validate every skill first; no partial catalog on any failure (contract requirement).
invalid_found=0
for ((i = 0; i < skill_count; i++)); do
	dir="${skill_dirs[$i]%/}"
	if ! "$SCRIPT_DIR/validate-skill.sh" "$dir" >/dev/null 2>/tmp/validate-skill-err.$$; then
		id="$(basename "$dir")"
		echo "ERROR: skill '$id' failed validation; catalog NOT regenerated:" >&2
		cat /tmp/validate-skill-err.$$ >&2
		invalid_found=1
	fi
	rm -f /tmp/validate-skill-err.$$
done
if [[ $invalid_found -ne 0 ]]; then
	exit 1
fi

# Preserve reviewer-maintained overlap_flags across regenerations (they are not derived from
# skills/ content; see skills/_authoring-standard.md's Manual Overlap Review section).
overlap_flags_lines=""
if [[ -f "$CATALOG_JSON" ]]; then
	overlap_flags_lines="$(awk '
		/"overlap_flags":[[:space:]]*\[/ {
			if ($0 ~ /\]/) { exit }
			capturing = 1
			next
		}
		capturing && /^[[:space:]]*\][[:space:]]*$/ { exit }
		capturing { print }
	' "$CATALOG_JSON")"
fi

generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

entries_json=""
first=1
for ((i = 0; i < skill_count; i++)); do
	dir="${skill_dirs[$i]%/}"
	id="$(basename "$dir")"
	skill_file="$dir/SKILL.md"
	name="$(fm_get "$skill_file" name || true)"
	description="$(fm_get "$skill_file" description || true)"
	usage="$(fm_get "$skill_file" usage || true)"
	compatibility="$(fm_get "$skill_file" compatibility || true)"
	[[ -z "$compatibility" ]] && compatibility="all"
	version="$(fm_get_nested "$skill_file" metadata version || true)"
	source_path="skills/$id/SKILL.md"

	entry=$(cat <<-ENTRY
		    {
		      "id": "$(printf '%s' "$id" | json_escape)",
		      "name": "$(printf '%s' "$name" | json_escape)",
		      "description": "$(printf '%s' "$description" | json_escape)",
		      "usage": "$(printf '%s' "$usage" | json_escape)",
		      "compatibility": "$(printf '%s' "$compatibility" | json_escape)",
		      "version": "$(printf '%s' "$version" | json_escape)",
		      "source_path": "$(printf '%s' "$source_path" | json_escape)"
		    }
	ENTRY
	)
	if [[ $first -eq 1 ]]; then
		entries_json="$entry"
		first=0
	else
		entries_json="${entries_json},"$'\n'"$entry"
	fi
done

mkdir -p "$CATALOG_DIR"

{
	echo "{"
	echo "  \"generated_at\": \"$generated_at\","
	if [[ -z "$entries_json" ]]; then
		echo "  \"entries\": [],"
	else
		echo "  \"entries\": ["
		echo "$entries_json"
		echo "  ],"
	fi
	if [[ -z "$overlap_flags_lines" ]]; then
		echo "  \"overlap_flags\": []"
	else
		echo "  \"overlap_flags\": ["
		echo "$overlap_flags_lines"
		echo "  ]"
	fi
	echo "}"
} >"$CATALOG_JSON"

# --- Human-readable catalog/index.md ---
{
	echo "# Skill Catalog"
	echo
	echo "Generated by \`.highway/tools/generate-catalog.sh\`. Do not hand-edit. See \`catalog/README.md\`."
	echo
	echo "_Generated at: ${generated_at}_"
	echo
	echo "| ID | Name | Description | Usage | Compatibility | Version |"
	echo "|---|---|---|---|---|---|"
	for ((i = 0; i < skill_count; i++)); do
		dir="${skill_dirs[$i]%/}"
		id="$(basename "$dir")"
		skill_file="$dir/SKILL.md"
		name="$(fm_get "$skill_file" name || true)"
		description="$(fm_get "$skill_file" description || true)"
		usage="$(fm_get "$skill_file" usage || true)"
		compatibility="$(fm_get "$skill_file" compatibility || true)"
		[[ -z "$compatibility" ]] && compatibility="all"
		version="$(fm_get_nested "$skill_file" metadata version || true)"
		echo "| $id | $name | $description | $usage | $compatibility | $version |"
	done
	echo
	echo "## Overlap Flags"
	echo
	if [[ -z "$overlap_flags_lines" ]]; then
		echo "None."
	else
		echo '```json'
		echo "$overlap_flags_lines"
		echo '```'
	fi
} >"$CATALOG_MD"

echo "OK: wrote $CATALOG_JSON and $CATALOG_MD (${skill_count} skill(s))"
exit 0
