#!/usr/bin/env bash
# Builds catalog/content-index.json + catalog/content-index.md from .highway/content/*/*.md
# frontmatter, per
# specs/004-shared-content-library/contracts/content-catalog.schema.json.
#
# Usage: .highway/tools/generate-content-catalog.sh
# Exit 0: catalog written.
# Exit 1: at least one file under .highway/content/ is invalid; the catalog is NOT written (no
#         partial catalog), and the failing file's path is named in the error output.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HIGHWAY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=tools/lib/frontmatter.sh
source "$SCRIPT_DIR/lib/frontmatter.sh"

CONTENT_DIR="$HIGHWAY_ROOT/content"
CATALOG_DIR="$HIGHWAY_ROOT/catalog"
CATALOG_JSON="$CATALOG_DIR/content-index.json"
CATALOG_MD="$CATALOG_DIR/content-index.md"

json_escape() {
	sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

# README.md documents the directory's purpose only; it is not itself shared content (FR-001).
content_files=()
shopt -s nullglob
for content_type in templates knowledge governance; do
	for f in "$CONTENT_DIR/$content_type"/*.md; do
		[[ "$(basename "$f")" == "README.md" ]] && continue
		content_files+=("$f")
	done
done
shopt -u nullglob
file_count=${#content_files[@]}

# Validate every file first; no partial catalog on any failure (contract requirement).
invalid_found=0
for ((i = 0; i < file_count; i++)); do
	f="${content_files[$i]}"
	if ! "$SCRIPT_DIR/validate-content.sh" "$f" >/dev/null 2>/tmp/validate-content-err.$$; then
		echo "ERROR: content '$f' failed validation; catalog NOT regenerated:" >&2
		cat /tmp/validate-content-err.$$ >&2
		invalid_found=1
	fi
	rm -f /tmp/validate-content-err.$$
done
if [[ $invalid_found -ne 0 ]]; then
	exit 1
fi

generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

content_type_of() {
	case "$1" in
		*/content/templates/*) echo "template" ;;
		*/content/knowledge/*) echo "knowledge" ;;
		*/content/governance/*) echo "governance" ;;
	esac
}

entries_json=""
first=1
for ((i = 0; i < file_count; i++)); do
	f="${content_files[$i]}"
	content_type="$(content_type_of "$f")"
	name="$(fm_get "$f" name || true)"
	description="$(fm_get "$f" description || true)"
	version="$(fm_get_nested "$f" metadata version || true)"
	source_path="content/${f#"$CONTENT_DIR"/}"

	entry=$(cat <<-ENTRY
		    {
		      "content_type": "$(printf '%s' "$content_type" | json_escape)",
		      "name": "$(printf '%s' "$name" | json_escape)",
		      "description": "$(printf '%s' "$description" | json_escape)",
		      "version": "$(printf '%s' "$version" | json_escape)",
		      "source_path": "$(printf '%s' "$source_path" | json_escape)"
		    }
	ENTRY
	)
	if [[ $first -eq 1 ]]; then
		entries_json="$entry"
		first=0
	else
		entries_json="${entries_json},"$'\n'"$entry"
	fi
done

mkdir -p "$CATALOG_DIR"

{
	echo "{"
	echo "  \"generated_at\": \"$generated_at\","
	if [[ -z "$entries_json" ]]; then
		echo "  \"entries\": []"
	else
		echo "  \"entries\": ["
		echo "$entries_json"
		echo "  ]"
	fi
	echo "}"
} >"$CATALOG_JSON"

# --- Human-readable catalog/content-index.md ---
{
	echo "# Shared Content Catalog"
	echo
	echo "Generated by \`.highway/tools/generate-content-catalog.sh\`. Do not hand-edit. See"
	echo "\`catalog/README.md\`."
	echo
	echo "_Generated at: ${generated_at}_"
	echo
	for content_type in template knowledge governance; do
		case "$content_type" in
			template) heading="Template" ;;
			knowledge) heading="Knowledge" ;;
			governance) heading="Governance" ;;
		esac
		echo "## ${heading}"
		echo
		echo "| Name | Description | Version | Source Path |"
		echo "|---|---|---|---|"
		for ((i = 0; i < file_count; i++)); do
			f="${content_files[$i]}"
			[[ "$(content_type_of "$f")" == "$content_type" ]] || continue
			name="$(fm_get "$f" name || true)"
			description="$(fm_get "$f" description || true)"
			version="$(fm_get_nested "$f" metadata version || true)"
			source_path="content/${f#"$CONTENT_DIR"/}"
			echo "| $name | $description | $version | $source_path |"
		done
		echo
	done
} >"$CATALOG_MD"

echo "OK: wrote $CATALOG_JSON and $CATALOG_MD (${file_count} content file(s))"
exit 0
